// lib/countries-data.ts

export interface Country {
    id: string;
    name: string;
    code: string;
    region: string;
    subregion: string;
    capital: string;
    population: number;
    area: number;
    languages: string[];
    currencies: string[];
    timezones: string[];
    flag: string;
    states: State[];
  }
  
  export interface State {
    id: string;
    name: string;
    capital?: string;
    code?: string;
    type?: "state" | "province" | "region" | "county" | "district" | "prefecture" | "governorate" | "territory" | "regional state" | "city" | "department" | "economic prefecture" | "dependency" | "commune";
    population?: number;
    area?: number;
  }

  
  
  // Complete African Countries Data
  export const africanCountries: Country[] = [
    // North Africa
    {
      id: "dz",
      name: "Algeria",
      code: "DZ",
      region: "North Africa",
      subregion: "North Africa",
      capital: "Algiers",
      population: 43851044,
      area: 2381741,
      languages: ["Arabic", "Berber", "French"],
      currencies: ["DZD"],
      timezones: ["UTC+1"],
      flag: "🇩🇿",
      states: [
        { id: "dz-01", name: "Adrar", type: "province" },
        { id: "dz-02", name: "Algiers", type: "province" },
        { id: "dz-03", name: "Annaba", type: "province" },
        { id: "dz-04", name: "Batna", type: "province" },
        { id: "dz-05", name: "Béjaïa", type: "province" },
        { id: "dz-06", name: "Biskra", type: "province" },
        { id: "dz-07", name: "Blida", type: "province" },
        { id: "dz-08", name: "Bordj Bou Arréridj", type: "province" },
        { id: "dz-09", name: "Bouira", type: "province" },
        { id: "dz-10", name: "Boumerdès", type: "province" },
        { id: "dz-11", name: "Chlef", type: "province" },
        { id: "dz-12", name: "Constantine", type: "province" },
        { id: "dz-13", name: "Djelfa", type: "province" },
        { id: "dz-14", name: "El Oued", type: "province" },
        { id: "dz-15", name: "El Tarf", type: "province" },
        { id: "dz-16", name: "Ghardaïa", type: "province" },
        { id: "dz-17", name: "Guelma", type: "province" },
        { id: "dz-18", name: "Illizi", type: "province" },
        { id: "dz-19", name: "Jijel", type: "province" },
        { id: "dz-20", name: "Khenchela", type: "province" },
        { id: "dz-21", name: "Laghouat", type: "province" },
        { id: "dz-22", name: "Médéa", type: "province" },
        { id: "dz-23", name: "Mila", type: "province" },
        { id: "dz-24", name: "Mostaganem", type: "province" },
        { id: "dz-25", name: "Msila", type: "province" },
        { id: "dz-26", name: "Naâma", type: "province" },
        { id: "dz-27", name: "Oran", type: "province" },
        { id: "dz-28", name: "Ouargla", type: "province" },
        { id: "dz-29", name: "Oum El Bouaghi", type: "province" },
        { id: "dz-30", name: "Relizane", type: "province" },
        { id: "dz-31", name: "Saïda", type: "province" },
        { id: "dz-32", name: "Sétif", type: "province" },
        { id: "dz-33", name: "Sidi Bel Abbès", type: "province" },
        { id: "dz-34", name: "Skikda", type: "province" },
        { id: "dz-35", name: "Souk Ahras", type: "province" },
        { id: "dz-36", name: "Tamanrasset", type: "province" },
        { id: "dz-37", name: "Tébessa", type: "province" },
        { id: "dz-38", name: "Tiaret", type: "province" },
        { id: "dz-39", name: "Tindouf", type: "province" },
        { id: "dz-40", name: "Tipaza", type: "province" },
        { id: "dz-41", name: "Tissemsilt", type: "province" },
        { id: "dz-42", name: "Tizi Ouzou", type: "province" },
        { id: "dz-43", name: "Tlemcen", type: "province" },
      ],
    },
    {
      id: "eg",
      name: "Egypt",
      code: "EG",
      region: "North Africa",
      subregion: "North Africa",
      capital: "Cairo",
      population: 102334404,
      area: 1002450,
      languages: ["Arabic"],
      currencies: ["EGP"],
      timezones: ["UTC+2"],
      flag: "🇪🇬",
      states: [
        { id: "eg-01", name: "Alexandria", type: "governorate" },
        { id: "eg-02", name: "Aswan", type: "governorate" },
        { id: "eg-03", name: "Asyut", type: "governorate" },
        { id: "eg-04", name: "Beheira", type: "governorate" },
        { id: "eg-05", name: "Beni Suef", type: "governorate" },
        { id: "eg-06", name: "Cairo", type: "governorate" },
        { id: "eg-07", name: "Dakahlia", type: "governorate" },
        { id: "eg-08", name: "Damietta", type: "governorate" },
        { id: "eg-09", name: "Faiyum", type: "governorate" },
        { id: "eg-10", name: "Gharbia", type: "governorate" },
        { id: "eg-11", name: "Giza", type: "governorate" },
        { id: "eg-12", name: "Ismailia", type: "governorate" },
        { id: "eg-13", name: "Kafr El Sheikh", type: "governorate" },
        { id: "eg-14", name: "Luxor", type: "governorate" },
        { id: "eg-15", name: "Matrouh", type: "governorate" },
        { id: "eg-16", name: "Minya", type: "governorate" },
        { id: "eg-17", name: "Monufia", type: "governorate" },
        { id: "eg-18", name: "New Valley", type: "governorate" },
        { id: "eg-19", name: "North Sinai", type: "governorate" },
        { id: "eg-20", name: "Port Said", type: "governorate" },
        { id: "eg-21", name: "Qalyubia", type: "governorate" },
        { id: "eg-22", name: "Qena", type: "governorate" },
        { id: "eg-23", name: "Red Sea", type: "governorate" },
        { id: "eg-24", name: "Sharqia", type: "governorate" },
        { id: "eg-25", name: "Sohag", type: "governorate" },
        { id: "eg-26", name: "South Sinai", type: "governorate" },
        { id: "eg-27", name: "Suez", type: "governorate" },
      ],
    },
    {
      id: "ly",
      name: "Libya",
      code: "LY",
      region: "North Africa",
      subregion: "North Africa",
      capital: "Tripoli",
      population: 6871292,
      area: 1759540,
      languages: ["Arabic", "Berber"],
      currencies: ["LYD"],
      timezones: ["UTC+2"],
      flag: "🇱🇾",
      states: [
        { id: "ly-01", name: "Benghazi", type: "district" },
        { id: "ly-02", name: "Butnan", type: "district" },
        { id: "ly-03", name: "Derna", type: "district" },
        { id: "ly-04", name: "Ghat", type: "district" },
        { id: "ly-05", name: "Jabal al Akhdar", type: "district" },
        { id: "ly-06", name: "Jabal al Gharbi", type: "district" },
        { id: "ly-07", name: "Jafara", type: "district" },
        { id: "ly-08", name: "Jufra", type: "district" },
        { id: "ly-09", name: "Kufra", type: "district" },
        { id: "ly-10", name: "Marj", type: "district" },
        { id: "ly-11", name: "Misrata", type: "district" },
        { id: "ly-12", name: "Murqub", type: "district" },
        { id: "ly-13", name: "Murzuq", type: "district" },
        { id: "ly-14", name: "Nalut", type: "district" },
        { id: "ly-15", name: "Nuqat al Khams", type: "district" },
        { id: "ly-16", name: "Sabha", type: "district" },
        { id: "ly-17", name: "Sirte", type: "district" },
        { id: "ly-18", name: "Tripoli", type: "district" },
        { id: "ly-19", name: "Wadi al Hayaa", type: "district" },
        { id: "ly-20", name: "Wadi al Shatii", type: "district" },
        { id: "ly-21", name: "Zawiya", type: "district" },
      ],
    },
    {
      id: "ma",
      name: "Morocco",
      code: "MA",
      region: "North Africa",
      subregion: "North Africa",
      capital: "Rabat",
      population: 36910560,
      area: 446550,
      languages: ["Arabic", "Berber", "French"],
      currencies: ["MAD"],
      timezones: ["UTC+1"],
      flag: "🇲🇦",
      states: [
        { id: "ma-01", name: "Agadir-Ida Ou Tanane", type: "prefecture" },
        { id: "ma-02", name: "Al Haouz", type: "province" },
        { id: "ma-03", name: "Al Hoceïma", type: "province" },
        { id: "ma-04", name: "Aousserd", type: "province" },
        { id: "ma-05", name: "Assa-Zag", type: "province" },
        { id: "ma-06", name: "Azilal", type: "province" },
        { id: "ma-07", name: "Ben Guerir", type: "province" },
        { id: "ma-08", name: "Beni Mellal", type: "province" },
        { id: "ma-09", name: "Berkane", type: "province" },
        { id: "ma-10", name: "Boujdour", type: "province" },
        { id: "ma-11", name: "Boulemane", type: "province" },
        { id: "ma-12", name: "Casablanca", type: "prefecture" },
        { id: "ma-13", name: "Chefchaouen", type: "province" },
        { id: "ma-14", name: "Chichaoua", type: "province" },
        { id: "ma-15", name: "Chtouka-Aït Baha", type: "province" },
        { id: "ma-16", name: "Dakhla-Oued Ed-Dahab", type: "region" },
        { id: "ma-17", name: "Drâa-Tafilalet", type: "region" },
        { id: "ma-18", name: "El Hajeb", type: "province" },
        { id: "ma-19", name: "El Jadida", type: "province" },
        { id: "ma-20", name: "Errachidia", type: "province" },
        { id: "ma-21", name: "Essaouira", type: "province" },
        { id: "ma-22", name: "Fahs-Anjra", type: "province" },
        { id: "ma-23", name: "Fez", type: "prefecture" },
        { id: "ma-24", name: "Figuig", type: "province" },
        { id: "ma-25", name: "Guelmim", type: "province" },
        { id: "ma-26", name: "Guelmim-Oued Noun", type: "region" },
        { id: "ma-27", name: "Ifrane", type: "province" },
        { id: "ma-28", name: "Inezgane-Aït Melloul", type: "prefecture" },
        { id: "ma-29", name: "Jerada", type: "province" },
        { id: "ma-30", name: "Kénitra", type: "province" },
        { id: "ma-31", name: "Khémisset", type: "province" },
        { id: "ma-32", name: "Khénifra", type: "province" },
        { id: "ma-33", name: "Khouribga", type: "province" },
        { id: "ma-34", name: "Laâyoune", type: "province" },
        { id: "ma-35", name: "Laâyoune-Sakia El Hamra", type: "region" },
        { id: "ma-36", name: "Larache", type: "province" },
        { id: "ma-37", name: "Marrakech", type: "prefecture" },
        { id: "ma-38", name: "Médiouna", type: "province" },
        { id: "ma-39", name: "Meknès", type: "prefecture" },
        { id: "ma-40", name: "Midelt", type: "province" },
        { id: "ma-41", name: "Moulay Yacoub", type: "province" },
        { id: "ma-42", name: "Nador", type: "province" },
        { id: "ma-43", name: "Nouaceur", type: "province" },
        { id: "ma-44", name: "Ouarzazate", type: "province" },
        { id: "ma-45", name: "Oued Ed-Dahab", type: "province" },
        { id: "ma-46", name: "Ouezzane", type: "province" },
        { id: "ma-47", name: "Rabat", type: "prefecture" },
        { id: "ma-48", name: "Rehamna", type: "province" },
        { id: "ma-49", name: "Safi", type: "province" },
        { id: "ma-50", name: "Salé", type: "prefecture" },
        { id: "ma-51", name: "Sefrou", type: "province" },
        { id: "ma-52", name: "Settat", type: "province" },
        { id: "ma-53", name: "Sidi Bennour", type: "province" },
        { id: "ma-54", name: "Sidi Ifni", type: "province" },
        { id: "ma-55", name: "Sidi Kacem", type: "province" },
        { id: "ma-56", name: "Sidi Slimane", type: "province" },
        { id: "ma-57", name: "Skhirate-Témara", type: "prefecture" },
        { id: "ma-58", name: "Tanger-Assilah", type: "prefecture" },
        { id: "ma-59", name: "Tan-Tan", type: "province" },
        { id: "ma-60", name: "Taounate", type: "province" },
        { id: "ma-61", name: "Taourirt", type: "province" },
        { id: "ma-62", name: "Tarfaya", type: "province" },
        { id: "ma-63", name: "Taroudant", type: "province" },
        { id: "ma-64", name: "Tata", type: "province" },
        { id: "ma-65", name: "Taza", type: "province" },
        { id: "ma-66", name: "Tétouan", type: "province" },
        { id: "ma-67", name: "Tinghir", type: "province" },
        { id: "ma-68", name: "Tiznit", type: "province" },
        { id: "ma-69", name: "Zagora", type: "province" },
      ],
    },
    {
      id: "sd",
      name: "Sudan",
      code: "SD",
      region: "North Africa",
      subregion: "North Africa",
      capital: "Khartoum",
      population: 43849269,
      area: 1861484,
      languages: ["Arabic", "English"],
      currencies: ["SDG"],
      timezones: ["UTC+2"],
      flag: "🇸🇩",
      states: [
        { id: "sd-01", name: "Al Jazirah", type: "state" },
        { id: "sd-02", name: "Al Qadarif", type: "state" },
        { id: "sd-03", name: "Blue Nile", type: "state" },
        { id: "sd-04", name: "Central Darfur", type: "state" },
        { id: "sd-05", name: "East Darfur", type: "state" },
        { id: "sd-06", name: "Kassala", type: "state" },
        { id: "sd-07", name: "Khartoum", type: "state" },
        { id: "sd-08", name: "North Darfur", type: "state" },
        { id: "sd-09", name: "North Kordofan", type: "state" },
        { id: "sd-10", name: "Northern", type: "state" },
        { id: "sd-11", name: "Red Sea", type: "state" },
        { id: "sd-12", name: "River Nile", type: "state" },
        { id: "sd-13", name: "Sennar", type: "state" },
        { id: "sd-14", name: "South Darfur", type: "state" },
        { id: "sd-15", name: "South Kordofan", type: "state" },
        { id: "sd-16", name: "West Darfur", type: "state" },
        { id: "sd-17", name: "West Kordofan", type: "state" },
        { id: "sd-18", name: "White Nile", type: "state" },
      ],
    },
    {
      id: "tn",
      name: "Tunisia",
      code: "TN",
      region: "North Africa",
      subregion: "North Africa",
      capital: "Tunis",
      population: 11818619,
      area: 163610,
      languages: ["Arabic", "French"],
      currencies: ["TND"],
      timezones: ["UTC+1"],
      flag: "🇹🇳",
      states: [
        { id: "tn-01", name: "Ariana", type: "governorate" },
        { id: "tn-02", name: "Béja", type: "governorate" },
        { id: "tn-03", name: "Ben Arous", type: "governorate" },
        { id: "tn-04", name: "Bizerte", type: "governorate" },
        { id: "tn-05", name: "Gabès", type: "governorate" },
        { id: "tn-06", name: "Gafsa", type: "governorate" },
        { id: "tn-07", name: "Jendouba", type: "governorate" },
        { id: "tn-08", name: "Kairouan", type: "governorate" },
        { id: "tn-09", name: "Kasserine", type: "governorate" },
        { id: "tn-10", name: "Kébili", type: "governorate" },
        { id: "tn-11", name: "La Manouba", type: "governorate" },
        { id: "tn-12", name: "Le Kef", type: "governorate" },
        { id: "tn-13", name: "Mahdia", type: "governorate" },
        { id: "tn-14", name: "Medenine", type: "governorate" },
        { id: "tn-15", name: "Monastir", type: "governorate" },
        { id: "tn-16", name: "Nabeul", type: "governorate" },
        { id: "tn-17", name: "Sfax", type: "governorate" },
        { id: "tn-18", name: "Sidi Bouzid", type: "governorate" },
        { id: "tn-19", name: "Siliana", type: "governorate" },
        { id: "tn-20", name: "Sousse", type: "governorate" },
        { id: "tn-21", name: "Tataouine", type: "governorate" },
        { id: "tn-22", name: "Tozeur", type: "governorate" },
        { id: "tn-23", name: "Tunis", type: "governorate" },
        { id: "tn-24", name: "Zaghouan", type: "governorate" },
      ],
    },
  
    // West Africa
    {
      id: "ng",
      name: "Nigeria",
      code: "NG",
      region: "West Africa",
      subregion: "West Africa",
      capital: "Abuja",
      population: 206139589,
      area: 923768,
      languages: ["English", "Hausa", "Yoruba", "Igbo"],
      currencies: ["NGN"],
      timezones: ["UTC+1"],
      flag: "🇳🇬",
      states: [
        { id: "ng-ab", name: "Abia", capital: "Umuahia", type: "state" },
        { id: "ng-ad", name: "Adamawa", capital: "Yola", type: "state" },
        { id: "ng-ak", name: "Akwa Ibom", capital: "Uyo", type: "state" },
        { id: "ng-an", name: "Anambra", capital: "Awka", type: "state" },
        { id: "ng-ba", name: "Bauchi", capital: "Bauchi", type: "state" },
        { id: "ng-by", name: "Bayelsa", capital: "Yenagoa", type: "state" },
        { id: "ng-be", name: "Benue", capital: "Makurdi", type: "state" },
        { id: "ng-bo", name: "Borno", capital: "Maiduguri", type: "state" },
        { id: "ng-cr", name: "Cross River", capital: "Calabar", type: "state" },
        { id: "ng-de", name: "Delta", capital: "Asaba", type: "state" },
        { id: "ng-eb", name: "Ebonyi", capital: "Abakaliki", type: "state" },
        { id: "ng-ed", name: "Edo", capital: "Benin City", type: "state" },
        { id: "ng-ek", name: "Ekiti", capital: "Ado Ekiti", type: "state" },
        { id: "ng-en", name: "Enugu", capital: "Enugu", type: "state" },
        { id: "ng-fc", name: "Federal Capital Territory", capital: "Abuja", type: "territory" },
        { id: "ng-go", name: "Gombe", capital: "Gombe", type: "state" },
        { id: "ng-im", name: "Imo", capital: "Owerri", type: "state" },
        { id: "ng-ji", name: "Jigawa", capital: "Dutse", type: "state" },
        { id: "ng-kd", name: "Kaduna", capital: "Kaduna", type: "state" },
        { id: "ng-kn", name: "Kano", capital: "Kano", type: "state" },
        { id: "ng-kt", name: "Katsina", capital: "Katsina", type: "state" },
        { id: "ng-ke", name: "Kebbi", capital: "Birnin Kebbi", type: "state" },
        { id: "ng-ko", name: "Kogi", capital: "Lokoja", type: "state" },
        { id: "ng-kw", name: "Kwara", capital: "Ilorin", type: "state" },
        { id: "ng-la", name: "Lagos", capital: "Ikeja", type: "state" },
        { id: "ng-na", name: "Nasarawa", capital: "Lafia", type: "state" },
        { id: "ng-ni", name: "Niger", capital: "Minna", type: "state" },
        { id: "ng-og", name: "Ogun", capital: "Abeokuta", type: "state" },
        { id: "ng-on", name: "Ondo", capital: "Akure", type: "state" },
        { id: "ng-os", name: "Osun", capital: "Oshogbo", type: "state" },
        { id: "ng-oy", name: "Oyo", capital: "Ibadan", type: "state" },
        { id: "ng-pl", name: "Plateau", capital: "Jos", type: "state" },
        { id: "ng-ri", name: "Rivers", capital: "Port Harcourt", type: "state" },
        { id: "ng-so", name: "Sokoto", capital: "Sokoto", type: "state" },
        { id: "ng-ta", name: "Taraba", capital: "Jalingo", type: "state" },
        { id: "ng-yo", name: "Yobe", capital: "Damaturu", type: "state" },
        { id: "ng-za", name: "Zamfara", capital: "Gusau", type: "state" },
      ],
    },
    {
      id: "gh",
      name: "Ghana",
      code: "GH",
      region: "West Africa",
      subregion: "West Africa",
      capital: "Accra",
      population: 31072940,
      area: 238533,
      languages: ["English"],
      currencies: ["GHS"],
      timezones: ["UTC+0"],
      flag: "🇬🇭",
      states: [
        { id: "gh-af", name: "Ahafo", capital: "Goaso", type: "region" },
        { id: "gh-ah", name: "Ashanti", capital: "Kumasi", type: "region" },
        { id: "gh-bo", name: "Bono", capital: "Sunyani", type: "region" },
        { id: "gh-be", name: "Bono East", capital: "Techiman", type: "region" },
        { id: "gh-cp", name: "Central", capital: "Cape Coast", type: "region" },
        { id: "gh-ep", name: "Eastern", capital: "Koforidua", type: "region" },
        { id: "gh-aa", name: "Greater Accra", capital: "Accra", type: "region" },
        { id: "gh-ne", name: "North East", capital: "Nalerigu", type: "region" },
        { id: "gh-np", name: "Northern", capital: "Tamale", type: "region" },
        { id: "gh-ot", name: "Oti", capital: "Dambai", type: "region" },
        { id: "gh-sv", name: "Savannah", capital: "Damongo", type: "region" },
        { id: "gh-ue", name: "Upper East", capital: "Bolgatanga", type: "region" },
        { id: "gh-uw", name: "Upper West", capital: "Wa", type: "region" },
        { id: "gh-vr", name: "Volta", capital: "Ho", type: "region" },
        { id: "gh-wp", name: "Western", capital: "Sekondi", type: "region" },
        { id: "gh-wn", name: "Western North", capital: "Wiawso", type: "region" },
      ],
    },
    {
      id: "ci",
      name: "Côte d'Ivoire",
      code: "CI",
      region: "West Africa",
      subregion: "West Africa",
      capital: "Yamoussoukro",
      population: 26378274,
      area: 322463,
      languages: ["French"],
      currencies: ["XOF"],
      timezones: ["UTC+0"],
      flag: "🇨🇮",
      states: [
        { id: "ci-ab", name: "Abidjan", type: "district" },
        { id: "ci-bs", name: "Bas-Sassandra", type: "district" },
        { id: "ci-cm", name: "Comoé", type: "district" },
        { id: "ci-dn", name: "Denguélé", type: "district" },
        { id: "ci-gd", name: "Gôh-Djiboua", type: "district" },
        { id: "ci-lc", name: "Lacs", type: "district" },
        { id: "ci-lg", name: "Lagunes", type: "district" },
        { id: "ci-mg", name: "Montagnes", type: "district" },
        { id: "ci-sm", name: "Sassandra-Marahoué", type: "district" },
        { id: "ci-sv", name: "Savanes", type: "district" },
        { id: "ci-vb", name: "Vallée du Bandama", type: "district" },
        { id: "ci-wr", name: "Woroba", type: "district" },
        { id: "ci-ym", name: "Yamoussoukro", type: "district" },
        { id: "ci-zz", name: "Zanzan", type: "district" },
      ],
    },
    {
      id: "sn",
      name: "Senegal",
      code: "SN",
      region: "West Africa",
      subregion: "West Africa",
      capital: "Dakar",
      population: 16743927,
      area: 196722,
      languages: ["French"],
      currencies: ["XOF"],
      timezones: ["UTC+0"],
      flag: "🇸🇳",
      states: [
        { id: "sn-dk", name: "Dakar", type: "region" },
        { id: "sn-db", name: "Diourbel", type: "region" },
        { id: "sn-fk", name: "Fatick", type: "region" },
        { id: "sn-kd", name: "Kaffrine", type: "region" },
        { id: "sn-kl", name: "Kaolack", type: "region" },
        { id: "sn-ke", name: "Kédougou", type: "region" },
        { id: "sn-kg", name: "Kolda", type: "region" },
        { id: "sn-lg", name: "Louga", type: "region" },
        { id: "sn-mt", name: "Matam", type: "region" },
        { id: "sn-sl", name: "Saint-Louis", type: "region" },
        { id: "sn-sc", name: "Sédhiou", type: "region" },
        { id: "sn-tc", name: "Tambacounda", type: "region" },
        { id: "sn-th", name: "Thiès", type: "region" },
        { id: "sn-zg", name: "Ziguinchor", type: "region" },
      ],
    },
  
    // East Africa
    {
      id: "ke",
      name: "Kenya",
      code: "KE",
      region: "East Africa",
      subregion: "East Africa",
      capital: "Nairobi",
      population: 53771296,
      area: 580367,
      languages: ["Swahili", "English"],
      currencies: ["KES"],
      timezones: ["UTC+3"],
      flag: "🇰🇪",
      states: [
        { id: "ke-01", name: "Mombasa", capital: "Mombasa", type: "county" },
        { id: "ke-02", name: "Kwale", capital: "Kwale", type: "county" },
        { id: "ke-03", name: "Kilifi", capital: "Kilifi", type: "county" },
        { id: "ke-04", name: "Tana River", capital: "Hola", type: "county" },
        { id: "ke-05", name: "Lamu", capital: "Lamu", type: "county" },
        { id: "ke-06", name: "Taita-Taveta", capital: "Voi", type: "county" },
        { id: "ke-07", name: "Garissa", capital: "Garissa", type: "county" },
        { id: "ke-08", name: "Wajir", capital: "Wajir", type: "county" },
        { id: "ke-09", name: "Mandera", capital: "Mandera", type: "county" },
        { id: "ke-10", name: "Marsabit", capital: "Marsabit", type: "county" },
        { id: "ke-11", name: "Isiolo", capital: "Isiolo", type: "county" },
        { id: "ke-12", name: "Meru", capital: "Meru", type: "county" },
        { id: "ke-13", name: "Tharaka-Nithi", capital: "Chuka", type: "county" },
        { id: "ke-14", name: "Embu", capital: "Embu", type: "county" },
        { id: "ke-15", name: "Kitui", capital: "Kitui", type: "county" },
        { id: "ke-16", name: "Machakos", capital: "Machakos", type: "county" },
        { id: "ke-17", name: "Makueni", capital: "Wote", type: "county" },
        { id: "ke-18", name: "Nyandarua", capital: "Ol Kalou", type: "county" },
        { id: "ke-19", name: "Nyeri", capital: "Nyeri", type: "county" },
        { id: "ke-20", name: "Kirinyaga", capital: "Kerugoya", type: "county" },
        { id: "ke-21", name: "Murang'a", capital: "Murang'a", type: "county" },
        { id: "ke-22", name: "Kiambu", capital: "Kiambu", type: "county" },
        { id: "ke-23", name: "Turkana", capital: "Lodwar", type: "county" },
        { id: "ke-24", name: "West Pokot", capital: "Kapenguria", type: "county" },
        { id: "ke-25", name: "Samburu", capital: "Maralal", type: "county" },
        { id: "ke-26", name: "Trans-Nzoia", capital: "Kitale", type: "county" },
        { id: "ke-27", name: "Uasin Gishu", capital: "Eldoret", type: "county" },
        { id: "ke-28", name: "Elgeyo-Marakwet", capital: "Iten", type: "county" },
        { id: "ke-29", name: "Nandi", capital: "Kapsabet", type: "county" },
        { id: "ke-30", name: "Baringo", capital: "Kabarnet", type: "county" },
        { id: "ke-31", name: "Laikipia", capital: "Rumuruti", type: "county" },
        { id: "ke-32", name: "Nakuru", capital: "Nakuru", type: "county" },
        { id: "ke-33", name: "Narok", capital: "Narok", type: "county" },
        { id: "ke-34", name: "Kajiado", capital: "Kajiado", type: "county" },
        { id: "ke-35", name: "Kericho", capital: "Kericho", type: "county" },
        { id: "ke-36", name: "Bomet", capital: "Bomet", type: "county" },
        { id: "ke-37", name: "Kakamega", capital: "Kakamega", type: "county" },
        { id: "ke-38", name: "Vihiga", capital: "Vihiga", type: "county" },
        { id: "ke-39", name: "Bungoma", capital: "Bungoma", type: "county" },
        { id: "ke-40", name: "Busia", capital: "Busia", type: "county" },
        { id: "ke-41", name: "Siaya", capital: "Siaya", type: "county" },
        { id: "ke-42", name: "Kisumu", capital: "Kisumu", type: "county" },
        { id: "ke-43", name: "Homa Bay", capital: "Homa Bay", type: "county" },
        { id: "ke-44", name: "Migori", capital: "Migori", type: "county" },
        { id: "ke-45", name: "Kisii", capital: "Kisii", type: "county" },
        { id: "ke-46", name: "Nyamira", capital: "Nyamira", type: "county" },
        { id: "ke-47", name: "Nairobi", capital: "Nairobi", type: "county" },
      ],
    },
    {
      id: "tz",
      name: "Tanzania",
      code: "TZ",
      region: "East Africa",
      subregion: "East Africa",
      capital: "Dodoma",
      population: 59734218,
      area: 945087,
      languages: ["Swahili", "English"],
      currencies: ["TZS"],
      timezones: ["UTC+3"],
      flag: "🇹🇿",
      states: [
        { id: "tz-01", name: "Arusha", type: "region" },
        { id: "tz-02", name: "Dar es Salaam", type: "region" },
        { id: "tz-03", name: "Dodoma", type: "region" },
        { id: "tz-04", name: "Geita", type: "region" },
        { id: "tz-05", name: "Iringa", type: "region" },
        { id: "tz-06", name: "Kagera", type: "region" },
        { id: "tz-07", name: "Katavi", type: "region" },
        { id: "tz-08", name: "Kigoma", type: "region" },
        { id: "tz-09", name: "Kilimanjaro", type: "region" },
        { id: "tz-10", name: "Lindi", type: "region" },
        { id: "tz-11", name: "Manyara", type: "region" },
        { id: "tz-12", name: "Mara", type: "region" },
        { id: "tz-13", name: "Mbeya", type: "region" },
        { id: "tz-14", name: "Morogoro", type: "region" },
        { id: "tz-15", name: "Mtwara", type: "region" },
        { id: "tz-16", name: "Mwanza", type: "region" },
        { id: "tz-17", name: "Njombe", type: "region" },
        { id: "tz-18", name: "Pemba North", type: "region" },
        { id: "tz-19", name: "Pemba South", type: "region" },
        { id: "tz-20", name: "Pwani", type: "region" },
        { id: "tz-21", name: "Rukwa", type: "region" },
        { id: "tz-22", name: "Ruvuma", type: "region" },
        { id: "tz-23", name: "Shinyanga", type: "region" },
        { id: "tz-24", name: "Simiyu", type: "region" },
        { id: "tz-25", name: "Singida", type: "region" },
        { id: "tz-26", name: "Songwe", type: "region" },
        { id: "tz-27", name: "Tabora", type: "region" },
        { id: "tz-28", name: "Tanga", type: "region" },
        { id: "tz-29", name: "Zanzibar North", type: "region" },
        { id: "tz-30", name: "Zanzibar South", type: "region" },
        { id: "tz-31", name: "Zanzibar West", type: "region" },
      ],
    },
    {
      id: "ug",
      name: "Uganda",
      code: "UG",
      region: "East Africa",
      subregion: "East Africa",
      capital: "Kampala",
      population: 45741007,
      area: 241038,
      languages: ["English", "Swahili"],
      currencies: ["UGX"],
      timezones: ["UTC+3"],
      flag: "🇺🇬",
      states: [
        { id: "ug-01", name: "Abim", type: "district" },
        { id: "ug-02", name: "Adjumani", type: "district" },
        { id: "ug-03", name: "Agago", type: "district" },
        { id: "ug-04", name: "Alebtong", type: "district" },
        { id: "ug-05", name: "Amolatar", type: "district" },
        { id: "ug-06", name: "Amudat", type: "district" },
        { id: "ug-07", name: "Amuria", type: "district" },
        { id: "ug-08", name: "Amuru", type: "district" },
        { id: "ug-09", name: "Apac", type: "district" },
        { id: "ug-10", name: "Arua", type: "district" },
        { id: "ug-11", name: "Budaka", type: "district" },
        { id: "ug-12", name: "Bududa", type: "district" },
        { id: "ug-13", name: "Bugiri", type: "district" },
        { id: "ug-14", name: "Buhweju", type: "district" },
        { id: "ug-15", name: "Buikwe", type: "district" },
        { id: "ug-16", name: "Bukedea", type: "district" },
        { id: "ug-17", name: "Bukomansimbi", type: "district" },
        { id: "ug-18", name: "Bukwo", type: "district" },
        { id: "ug-19", name: "Bulambuli", type: "district" },
        { id: "ug-20", name: "Buliisa", type: "district" },
        { id: "ug-21", name: "Bundibugyo", type: "district" },
        { id: "ug-22", name: "Bunyangabu", type: "district" },
        { id: "ug-23", name: "Bushenyi", type: "district" },
        { id: "ug-24", name: "Busia", type: "district" },
        { id: "ug-25", name: "Butaleja", type: "district" },
        { id: "ug-26", name: "Butambala", type: "district" },
        { id: "ug-27", name: "Butebo", type: "district" },
        { id: "ug-28", name: "Buvuma", type: "district" },
        { id: "ug-29", name: "Buyende", type: "district" },
        { id: "ug-30", name: "Dokolo", type: "district" },
        { id: "ug-31", name: "Gomba", type: "district" },
        { id: "ug-32", name: "Gulu", type: "district" },
        { id: "ug-33", name: "Hoima", type: "district" },
        { id: "ug-34", name: "Ibanda", type: "district" },
        { id: "ug-35", name: "Iganga", type: "district" },
        { id: "ug-36", name: "Isingiro", type: "district" },
        { id: "ug-37", name: "Jinja", type: "district" },
        { id: "ug-38", name: "Kaabong", type: "district" },
        { id: "ug-39", name: "Kabale", type: "district" },
        { id: "ug-40", name: "Kabarole", type: "district" },
        { id: "ug-41", name: "Kaberamaido", type: "district" },
        { id: "ug-42", name: "Kagadi", type: "district" },
        { id: "ug-43", name: "Kakumiro", type: "district" },
        { id: "ug-44", name: "Kalangala", type: "district" },
        { id: "ug-45", name: "Kaliro", type: "district" },
        { id: "ug-46", name: "Kalungu", type: "district" },
        { id: "ug-47", name: "Kampala", type: "city" },
        { id: "ug-48", name: "Kamuli", type: "district" },
        { id: "ug-49", name: "Kamwenge", type: "district" },
        { id: "ug-50", name: "Kanungu", type: "district" },
        { id: "ug-51", name: "Kapchorwa", type: "district" },
        { id: "ug-52", name: "Kapelebyong", type: "district" },
        { id: "ug-53", name: "Kasanda", type: "district" },
        { id: "ug-54", name: "Katakwi", type: "district" },
        { id: "ug-55", name: "Kayunga", type: "district" },
        { id: "ug-56", name: "Kibaale", type: "district" },
        { id: "ug-57", name: "Kiboga", type: "district" },
        { id: "ug-58", name: "Kibuku", type: "district" },
        { id: "ug-59", name: "Kiruhura", type: "district" },
        { id: "ug-60", name: "Kiryandongo", type: "district" },
        { id: "ug-61", name: "Kisoro", type: "district" },
        { id: "ug-62", name: "Kitgum", type: "district" },
        { id: "ug-63", name: "Koboko", type: "district" },
        { id: "ug-64", name: "Kole", type: "district" },
        { id: "ug-65", name: "Kotido", type: "district" },
        { id: "ug-66", name: "Kumi", type: "district" },
        { id: "ug-67", name: "Kween", type: "district" },
        { id: "ug-68", name: "Kyaka", type: "district" },
        { id: "ug-69", name: "Kyankwanzi", type: "district" },
        { id: "ug-70", name: "Kyegegwa", type: "district" },
        { id: "ug-71", name: "Kyenjojo", type: "district" },
        { id: "ug-72", name: "Lamwo", type: "district" },
        { id: "ug-73", name: "Lira", type: "district" },
        { id: "ug-74", name: "Luuka", type: "district" },
        { id: "ug-75", name: "Luwero", type: "district" },
        { id: "ug-76", name: "Lwengo", type: "district" },
        { id: "ug-77", name: "Lyantonde", type: "district" },
        { id: "ug-78", name: "Manafwa", type: "district" },
        { id: "ug-79", name: "Maracha", type: "district" },
        { id: "ug-80", name: "Masaka", type: "district" },
        { id: "ug-81", name: "Masindi", type: "district" },
        { id: "ug-82", name: "Mayuge", type: "district" },
        { id: "ug-83", name: "Mbale", type: "district" },
        { id: "ug-84", name: "Mbarara", type: "district" },
        { id: "ug-85", name: "Mitooma", type: "district" },
        { id: "ug-86", name: "Mityana", type: "district" },
        { id: "ug-87", name: "Moroto", type: "district" },
        { id: "ug-88", name: "Moyo", type: "district" },
        { id: "ug-89", name: "Mpigi", type: "district" },
        { id: "ug-90", name: "Mubende", type: "district" },
        { id: "ug-91", name: "Mukono", type: "district" },
        { id: "ug-92", name: "Nakapiripirit", type: "district" },
        { id: "ug-93", name: "Nakaseke", type: "district" },
        { id: "ug-94", name: "Nakasongola", type: "district" },
        { id: "ug-95", name: "Namayingo", type: "district" },
        { id: "ug-96", name: "Namisindwa", type: "district" },
        { id: "ug-97", name: "Namutumba", type: "district" },
        { id: "ug-98", name: "Napak", type: "district" },
        { id: "ug-99", name: "Nebbi", type: "district" },
        { id: "ug-100", name: "Ngora", type: "district" },
        { id: "ug-101", name: "Ntoroko", type: "district" },
        { id: "ug-102", name: "Ntungamo", type: "district" },
        { id: "ug-103", name: "Nwoya", type: "district" },
        { id: "ug-104", name: "Omoro", type: "district" },
        { id: "ug-105", name: "Otuke", type: "district" },
        { id: "ug-106", name: "Oyam", type: "district" },
        { id: "ug-107", name: "Pader", type: "district" },
        { id: "ug-108", name: "Pakwach", type: "district" },
        { id: "ug-109", name: "Pallisa", type: "district" },
        { id: "ug-110", name: "Rakai", type: "district" },
        { id: "ug-111", name: "Rubanda", type: "district" },
        { id: "ug-112", name: "Rubirizi", type: "district" },
        { id: "ug-113", name: "Rukiga", type: "district" },
        { id: "ug-114", name: "Rukungiri", type: "district" },
        { id: "ug-115", name: "Sembabule", type: "district" },
        { id: "ug-116", name: "Serere", type: "district" },
        { id: "ug-117", name: "Sheema", type: "district" },
        { id: "ug-118", name: "Sironko", type: "district" },
        { id: "ug-119", name: "Soroti", type: "district" },
        { id: "ug-120", name: "Tororo", type: "district" },
        { id: "ug-121", name: "Wakiso", type: "district" },
        { id: "ug-122", name: "Yumbe", type: "district" },
        { id: "ug-123", name: "Zombo", type: "district" },
      ],
    },
    {
      id: "rw",
      name: "Rwanda",
      code: "RW",
      region: "East Africa",
      subregion: "East Africa",
      capital: "Kigali",
      population: 12952218,
      area: 26338,
      languages: ["Kinyarwanda", "English", "French"],
      currencies: ["RWF"],
      timezones: ["UTC+2"],
      flag: "🇷🇼",
      states: [
        { id: "rw-01", name: "Kigali", capital: "Kigali", type: "province" },
        { id: "rw-02", name: "Eastern", capital: "Rwamagana", type: "province" },
        { id: "rw-03", name: "Northern", capital: "Musanze", type: "province" },
        { id: "rw-04", name: "Southern", capital: "Nyanza", type: "province" },
        { id: "rw-05", name: "Western", capital: "Kibuye", type: "province" },
      ],
    },
    {
      id: "et",
      name: "Ethiopia",
      code: "ET",
      region: "East Africa",
      subregion: "East Africa",
      capital: "Addis Ababa",
      population: 114963588,
      area: 1104300,
      languages: ["Amharic", "Oromo", "Tigrinya", "Somali"],
      currencies: ["ETB"],
      timezones: ["UTC+3"],
      flag: "🇪🇹",
      states: [
        { id: "et-aa", name: "Addis Ababa", type: "city" },
        { id: "et-af", name: "Afar", type: "regional state" },
        { id: "et-am", name: "Amhara", type: "regional state" },
        { id: "et-be", name: "Benishangul-Gumuz", type: "regional state" },
        { id: "et-dd", name: "Dire Dawa", type: "city" },
        { id: "et-ga", name: "Gambela", type: "regional state" },
        { id: "et-ha", name: "Harari", type: "regional state" },
        { id: "et-or", name: "Oromia", type: "regional state" },
        { id: "et-si", name: "Sidama", type: "regional state" },
        { id: "et-so", name: "Somali", type: "regional state" },
        { id: "et-sw", name: "South West Ethiopia", type: "regional state" },
        { id: "et-ti", name: "Tigray", type: "regional state" },
        { id: "et-sn", name: "Southern Nations, Nationalities, and Peoples' Region", type: "regional state" },
      ],
    },
    {
      id: "so",
      name: "Somalia",
      code: "SO",
      region: "East Africa",
      subregion: "East Africa",
      capital: "Mogadishu",
      population: 15893222,
      area: 637657,
      languages: ["Somali", "Arabic"],
      currencies: ["SOS"],
      timezones: ["UTC+3"],
      flag: "🇸🇴",
      states: [
        { id: "so-bn", name: "Banaadir", type: "region" },
        { id: "so-br", name: "Bari", type: "region" },
        { id: "so-by", name: "Bay", type: "region" },
        { id: "so-ga", name: "Galguduud", type: "region" },
        { id: "so-ge", name: "Gedo", type: "region" },
        { id: "so-hi", name: "Hiran", type: "region" },
        { id: "so-jd", name: "Jubbada Dhexe", type: "region" },
        { id: "so-jh", name: "Jubbada Hoose", type: "region" },
        { id: "so-mu", name: "Mudug", type: "region" },
        { id: "so-nu", name: "Nugaal", type: "region" },
        { id: "so-sa", name: "Sanaag", type: "region" },
        { id: "so-sd", name: "Shabeellaha Dhexe", type: "region" },
        { id: "so-sh", name: "Shabeellaha Hoose", type: "region" },
        { id: "so-so", name: "Sool", type: "region" },
        { id: "so-to", name: "Togdheer", type: "region" },
        { id: "so-wo", name: "Woqooyi Galbeed", type: "region" },
      ],
    },
  
    // Southern Africa
    {
      id: "za",
      name: "South Africa",
      code: "ZA",
      region: "Southern Africa",
      subregion: "Southern Africa",
      capital: "Pretoria",
      population: 59308690,
      area: 1221037,
      languages: ["Zulu", "Xhosa", "Afrikaans", "English", "Northern Sotho", "Tswana", "Sotho", "Tsonga", "Swazi", "Venda", "Southern Ndebele"],
      currencies: ["ZAR"],
      timezones: ["UTC+2"],
      flag: "🇿🇦",
      states: [
        { id: "za-ec", name: "Eastern Cape", capital: "Bhisho", type: "province" },
        { id: "za-fs", name: "Free State", capital: "Bloemfontein", type: "province" },
        { id: "za-gt", name: "Gauteng", capital: "Johannesburg", type: "province" },
        { id: "za-nl", name: "KwaZulu-Natal", capital: "Pietermaritzburg", type: "province" },
        { id: "za-lp", name: "Limpopo", capital: "Polokwane", type: "province" },
        { id: "za-mp", name: "Mpumalanga", capital: "Nelspruit", type: "province" },
        { id: "za-nw", name: "North West", capital: "Mahikeng", type: "province" },
        { id: "za-nc", name: "Northern Cape", capital: "Kimberley", type: "province" },
        { id: "za-wc", name: "Western Cape", capital: "Cape Town", type: "province" },
      ],
    },
    {
      id: "zm",
      name: "Zambia",
      code: "ZM",
      region: "Southern Africa",
      subregion: "Southern Africa",
      capital: "Lusaka",
      population: 18383955,
      area: 752612,
      languages: ["English"],
      currencies: ["ZMW"],
      timezones: ["UTC+2"],
      flag: "🇿🇲",
      states: [
        { id: "zm-01", name: "Central", capital: "Kabwe", type: "province" },
        { id: "zm-02", name: "Copperbelt", capital: "Ndola", type: "province" },
        { id: "zm-03", name: "Eastern", capital: "Chipata", type: "province" },
        { id: "zm-04", name: "Luapula", capital: "Mansa", type: "province" },
        { id: "zm-05", name: "Lusaka", capital: "Lusaka", type: "province" },
        { id: "zm-06", name: "Muchinga", capital: "Chinsali", type: "province" },
        { id: "zm-07", name: "Northern", capital: "Kasama", type: "province" },
        { id: "zm-08", name: "North-Western", capital: "Solwezi", type: "province" },
        { id: "zm-09", name: "Southern", capital: "Choma", type: "province" },
        { id: "zm-10", name: "Western", capital: "Mongu", type: "province" },
      ],
    },
    {
      id: "zw",
      name: "Zimbabwe",
      code: "ZW",
      region: "Southern Africa",
      subregion: "Southern Africa",
      capital: "Harare",
      population: 14862924,
      area: 390757,
      languages: ["English", "Shona", "Ndebele"],
      currencies: ["USD", "ZWL"],
      timezones: ["UTC+2"],
      flag: "🇿🇼",
      states: [
        { id: "zw-bu", name: "Bulawayo", type: "province" },
        { id: "zw-ha", name: "Harare", type: "province" },
        { id: "zw-ma", name: "Manicaland", capital: "Mutare", type: "province" },
        { id: "zw-mc", name: "Mashonaland Central", capital: "Bindura", type: "province" },
        { id: "zw-me", name: "Mashonaland East", capital: "Marondera", type: "province" },
        { id: "zw-mw", name: "Mashonaland West", capital: "Chinhoyi", type: "province" },
        { id: "zw-mv", name: "Masvingo", capital: "Masvingo", type: "province" },
        { id: "zw-mn", name: "Matabeleland North", capital: "Lupane", type: "province" },
        { id: "zw-ms", name: "Matabeleland South", capital: "Gwanda", type: "province" },
        { id: "zw-mt", name: "Midlands", capital: "Gweru", type: "province" },
      ],
    },
    {
      id: "mw",
      name: "Malawi",
      code: "MW",
      region: "Southern Africa",
      subregion: "Southern Africa",
      capital: "Lilongwe",
      population: 19129955,
      area: 118484,
      languages: ["English", "Chichewa"],
      currencies: ["MWK"],
      timezones: ["UTC+2"],
      flag: "🇲🇼",
      states: [
        { id: "mw-ba", name: "Balaka", type: "district" },
        { id: "mw-bl", name: "Blantyre", type: "district" },
        { id: "mw-ck", name: "Chikwawa", type: "district" },
        { id: "mw-cr", name: "Chiradzulu", type: "district" },
        { id: "mw-ct", name: "Chitipa", type: "district" },
        { id: "mw-de", name: "Dedza", type: "district" },
        { id: "mw-do", name: "Dowa", type: "district" },
        { id: "mw-kr", name: "Karonga", type: "district" },
        { id: "mw-ks", name: "Kasungu", type: "district" },
        { id: "mw-lk", name: "Likoma", type: "district" },
        { id: "mw-li", name: "Lilongwe", type: "district" },
        { id: "mw-mh", name: "Machinga", type: "district" },
        { id: "mw-mg", name: "Mangochi", type: "district" },
        { id: "mw-mc", name: "Mchinji", type: "district" },
        { id: "mw-mu", name: "Mulanje", type: "district" },
        { id: "mw-mw", name: "Mwanza", type: "district" },
        { id: "mw-mz", name: "Mzimba", type: "district" },
        { id: "mw-ne", name: "Neno", type: "district" },
        { id: "mw-nb", name: "Nkhata Bay", type: "district" },
        { id: "mw-nk", name: "Nkhotakota", type: "district" },
        { id: "mw-ns", name: "Nsanje", type: "district" },
        { id: "mw-nu", name: "Ntcheu", type: "district" },
        { id: "mw-ni", name: "Ntchisi", type: "district" },
        { id: "mw-ph", name: "Phalombe", type: "district" },
        { id: "mw-ru", name: "Rumphi", type: "district" },
        { id: "mw-sa", name: "Salima", type: "district" },
        { id: "mw-th", name: "Thyolo", type: "district" },
        { id: "mw-zo", name: "Zomba", type: "district" },
      ],
    },
    {
      id: "ao",
      name: "Angola",
      code: "AO",
      region: "Southern Africa",
      subregion: "Southern Africa",
      capital: "Luanda",
      population: 32866272,
      area: 1246700,
      languages: ["Portuguese"],
      currencies: ["AOA"],
      timezones: ["UTC+1"],
      flag: "🇦🇴",
      states: [
        { id: "ao-bgo", name: "Bengo", capital: "Caxito", type: "province" },
        { id: "ao-bgu", name: "Benguela", capital: "Benguela", type: "province" },
        { id: "ao-bie", name: "Bié", capital: "Kuito", type: "province" },
        { id: "ao-cab", name: "Cabinda", capital: "Cabinda", type: "province" },
        { id: "ao-ccu", name: "Cuando Cubango", capital: "Menongue", type: "province" },
        { id: "ao-cno", name: "Cuanza Norte", capital: "Ndalatando", type: "province" },
        { id: "ao-cus", name: "Cuanza Sul", capital: "Sumbe", type: "province" },
        { id: "ao-cnn", name: "Cunene", capital: "Ondjiva", type: "province" },
        { id: "ao-hua", name: "Huambo", capital: "Huambo", type: "province" },
        { id: "ao-hui", name: "Huíla", capital: "Lubango", type: "province" },
        { id: "ao-lua", name: "Luanda", capital: "Luanda", type: "province" },
        { id: "ao-lno", name: "Lunda Norte", capital: "Dundo", type: "province" },
        { id: "ao-lsu", name: "Lunda Sul", capital: "Saurimo", type: "province" },
        { id: "ao-mal", name: "Malanje", capital: "Malanje", type: "province" },
        { id: "ao-mox", name: "Moxico", capital: "Luena", type: "province" },
        { id: "ao-nam", name: "Namibe", capital: "Namibe", type: "province" },
        { id: "ao-uig", name: "Uíge", capital: "Uíge", type: "province" },
        { id: "ao-zai", name: "Zaire", capital: "Mbanza Kongo", type: "province" },
      ],
    },
    {
      id: "bw",
      name: "Botswana",
      code: "BW",
      region: "Southern Africa",
      subregion: "Southern Africa",
      capital: "Gaborone",
      population: 2351627,
      area: 581730,
      languages: ["English", "Tswana"],
      currencies: ["BWP"],
      timezones: ["UTC+2"],
      flag: "🇧🇼",
      states: [
        { id: "bw-ce", name: "Central", capital: "Serowe", type: "district" },
        { id: "bw-gh", name: "Ghanzi", capital: "Ghanzi", type: "district" },
        { id: "bw-kg", name: "Kgalagadi", capital: "Tsabong", type: "district" },
        { id: "bw-kl", name: "Kgatleng", capital: "Mochudi", type: "district" },
        { id: "bw-kw", name: "Kweneng", capital: "Molepolole", type: "district" },
        { id: "bw-ne", name: "North-East", capital: "Masunga", type: "district" },
        { id: "bw-nw", name: "North-West", capital: "Maun", type: "district" },
        { id: "bw-se", name: "South-East", capital: "Gaborone", type: "district" },
        { id: "bw-so", name: "Southern", capital: "Kanye", type: "district" },
      ],
    },
    {
      id: "na",
      name: "Namibia",
      code: "NA",
      region: "Southern Africa",
      subregion: "Southern Africa",
      capital: "Windhoek",
      population: 2540905,
      area: 825615,
      languages: ["English"],
      currencies: ["NAD", "ZAR"],
      timezones: ["UTC+2"],
      flag: "🇳🇦",
      states: [
        { id: "na-er", name: "Erongo", capital: "Swakopmund", type: "region" },
        { id: "na-ha", name: "Hardap", capital: "Mariental", type: "region" },
        { id: "na-ka", name: "Karas", capital: "Keetmanshoop", type: "region" },
        { id: "na-kv", name: "Kavango East", capital: "Rundu", type: "region" },
        { id: "na-kw", name: "Kavango West", capital: "Nkurenkuru", type: "region" },
        { id: "na-kh", name: "Khomas", capital: "Windhoek", type: "region" },
        { id: "na-kun", name: "Kunene", capital: "Opuwo", type: "region" },
        { id: "na-ow", name: "Ohangwena", capital: "Eenhana", type: "region" },
        { id: "na-oh", name: "Omaheke", capital: "Gobabis", type: "region" },
        { id: "na-os", name: "Omusati", capital: "Outapi", type: "region" },
        { id: "na-on", name: "Oshana", capital: "Oshakati", type: "region" },
        { id: "na-ot", name: "Oshikoto", capital: "Omuthiya", type: "region" },
        { id: "na-od", name: "Otjozondjupa", capital: "Otjiwarongo", type: "region" },
        { id: "na-ca", name: "Zambezi", capital: "Katima Mulilo", type: "region" },
      ],
    },
    {
      id: "mu",
      name: "Mauritius",
      code: "MU",
      region: "Island States",
      subregion: "Eastern Africa",
      capital: "Port Louis",
      population: 1271768,
      area: 2040,
      languages: ["English", "French", "Mauritian Creole"],
      currencies: ["MUR"],
      timezones: ["UTC+4"],
      flag: "🇲🇺",
      states: [
        { id: "mu-ag", name: "Agalega", type: "dependency" },
        { id: "mu-bl", name: "Black River", capital: "Bambous", type: "district" },
        { id: "mu-fl", name: "Flacq", capital: "Centre de Flacq", type: "district" },
        { id: "mu-gp", name: "Grand Port", capital: "Mahébourg", type: "district" },
        { id: "mu-mo", name: "Moka", capital: "Quartier Militaire", type: "district" },
        { id: "mu-pa", name: "Pamplemousses", capital: "Triolet", type: "district" },
        { id: "mu-pw", name: "Plaines Wilhems", capital: "Beau Bassin-Rose Hill", type: "district" },
        { id: "mu-pl", name: "Port Louis", capital: "Port Louis", type: "district" },
        { id: "mu-rr", name: "Rivière du Rempart", capital: "Mapou", type: "district" },
        { id: "mu-sa", name: "Savanne", capital: "Souillac", type: "district" },
        { id: "mu-ro", name: "Rodrigues", type: "dependency" },
      ],
    },
    {
      id: "sc",
      name: "Seychelles",
      code: "SC",
      region: "Island States",
      subregion: "Eastern Africa",
      capital: "Victoria",
      population: 98347,
      area: 455,
      languages: ["Seychellois Creole", "English", "French"],
      currencies: ["SCR"],
      timezones: ["UTC+4"],
      flag: "🇸🇨",
      states: [
        { id: "sc-01", name: "Anse aux Pins", type: "district" },
        { id: "sc-02", name: "Anse Boileau", type: "district" },
        { id: "sc-03", name: "Anse Etoile", type: "district" },
        { id: "sc-04", name: "Anse Royale", type: "district" },
        { id: "sc-05", name: "Au Cap", type: "district" },
        { id: "sc-06", name: "Baie Lazare", type: "district" },
        { id: "sc-07", name: "Baie Sainte Anne", type: "district" },
        { id: "sc-08", name: "Beau Vallon", type: "district" },
        { id: "sc-09", name: "Bel Air", type: "district" },
        { id: "sc-10", name: "Bel Ombre", type: "district" },
        { id: "sc-11", name: "Cascade", type: "district" },
        { id: "sc-12", name: "Glacis", type: "district" },
        { id: "sc-13", name: "Grand Anse Mahé", type: "district" },
        { id: "sc-14", name: "Grand Anse Praslin", type: "district" },
        { id: "sc-15", name: "La Digue", type: "district" },
        { id: "sc-16", name: "Les Mamelles", type: "district" },
        { id: "sc-17", name: "Mont Buxton", type: "district" },
        { id: "sc-18", name: "Mont Fleuri", type: "district" },
        { id: "sc-19", name: "Plaisance", type: "district" },
        { id: "sc-20", name: "Pointe Larue", type: "district" },
        { id: "sc-21", name: "Port Glaud", type: "district" },
        { id: "sc-22", name: "Roche Caiman", type: "district" },
        { id: "sc-23", name: "Saint Louis", type: "district" },
        { id: "sc-24", name: "Takamaka", type: "district" },
      ],
    },
  ];
  
  // Central Africa
  export const centralAfricanCountries: Country[] = [
    {
      id: "cm",
      name: "Cameroon",
      code: "CM",
      region: "Central Africa",
      subregion: "Central Africa",
      capital: "Yaoundé",
      population: 26545863,
      area: 475442,
      languages: ["English", "French"],
      currencies: ["XAF"],
      timezones: ["UTC+1"],
      flag: "🇨🇲",
      states: [
        { id: "cm-ad", name: "Adamawa", capital: "Ngaoundéré", type: "region" },
        { id: "cm-ce", name: "Centre", capital: "Yaoundé", type: "region" },
        { id: "cm-en", name: "East", capital: "Bertoua", type: "region" },
        { id: "cm-es", name: "Extreme North", capital: "Maroua", type: "region" },
        { id: "cm-lt", name: "Littoral", capital: "Douala", type: "region" },
        { id: "cm-no", name: "North", capital: "Garoua", type: "region" },
        { id: "cm-nw", name: "Northwest", capital: "Bamenda", type: "region" },
        { id: "cm-su", name: "South", capital: "Ebolowa", type: "region" },
        { id: "cm-sw", name: "Southwest", capital: "Buea", type: "region" },
        { id: "cm-ou", name: "West", capital: "Bafoussam", type: "region" },
      ],
    },
    {
      id: "cd",
      name: "DR Congo",
      code: "CD",
      region: "Central Africa",
      subregion: "Central Africa",
      capital: "Kinshasa",
      population: 89561403,
      area: 2344858,
      languages: ["French"],
      currencies: ["CDF"],
      timezones: ["UTC+1", "UTC+2"],
      flag: "🇨🇩",
      states: [
        { id: "cd-bu", name: "Bas-Uélé", capital: "Buta", type: "province" },
        { id: "cd-eq", name: "Équateur", capital: "Mbandaka", type: "province" },
        { id: "cd-hk", name: "Haut-Katanga", capital: "Lubumbashi", type: "province" },
        { id: "cd-hl", name: "Haut-Lomami", capital: "Kamina", type: "province" },
        { id: "cd-hu", name: "Haut-Uélé", capital: "Isiro", type: "province" },
        { id: "cd-it", name: "Ituri", capital: "Bunia", type: "province" },
        { id: "cd-ks", name: "Kasaï", capital: "Luebo", type: "province" },
        { id: "cd-kc", name: "Kasaï-Central", capital: "Kananga", type: "province" },
        { id: "cd-ke", name: "Kasaï-Oriental", capital: "Mbuji-Mayi", type: "province" },
        { id: "cd-kn", name: "Kinshasa", capital: "Kinshasa", type: "city" },
        { id: "cd-kg", name: "Kongo Central", capital: "Matadi", type: "province" },
        { id: "cd-kv", name: "Kwango", capital: "Kenge", type: "province" },
        { id: "cd-kw", name: "Kwilu", capital: "Bandundu", type: "province" },
        { id: "cd-lo", name: "Lomami", capital: "Kabinda", type: "province" },
        { id: "cd-lu", name: "Lualaba", capital: "Kolwezi", type: "province" },
        { id: "cd-mn", name: "Mai-Ndombe", capital: "Inongo", type: "province" },
        { id: "cd-mn", name: "Maniema", capital: "Kindu", type: "province" },
        { id: "cd-mo", name: "Mongala", capital: "Lisala", type: "province" },
        { id: "cd-nk", name: "Nord-Kivu", capital: "Goma", type: "province" },
        { id: "cd-nu", name: "Nord-Ubangi", capital: "Gbadolite", type: "province" },
        { id: "cd-sa", name: "Sankuru", capital: "Lusambo", type: "province" },
        { id: "cd-sk", name: "Sud-Kivu", capital: "Bukavu", type: "province" },
        { id: "cd-su", name: "Sud-Ubangi", capital: "Gemena", type: "province" },
        { id: "cd-ta", name: "Tanganyika", capital: "Kalemie", type: "province" },
        { id: "cd-to", name: "Tshopo", capital: "Kisangani", type: "province" },
        { id: "cd-tu", name: "Tshuapa", capital: "Boende", type: "province" },
      ],
    },
    {
      id: "cg",
      name: "Republic of Congo",
      code: "CG",
      region: "Central Africa",
      subregion: "Central Africa",
      capital: "Brazzaville",
      population: 5518092,
      area: 342000,
      languages: ["French"],
      currencies: ["XAF"],
      timezones: ["UTC+1"],
      flag: "🇨🇬",
      states: [
        { id: "cg-11", name: "Bouenza", capital: "Madingou", type: "department" },
        { id: "cg-12", name: "Brazzaville", capital: "Brazzaville", type: "department" },
        { id: "cg-13", name: "Cuvette", capital: "Owando", type: "department" },
        { id: "cg-14", name: "Cuvette-Ouest", capital: "Ewo", type: "department" },
        { id: "cg-15", name: "Kouilou", capital: "Pointe-Noire", type: "department" },
        { id: "cg-16", name: "Lékoumou", capital: "Sibiti", type: "department" },
        { id: "cg-17", name: "Likouala", capital: "Impfondo", type: "department" },
        { id: "cg-18", name: "Niari", capital: "Dolisie", type: "department" },
        { id: "cg-19", name: "Plateaux", capital: "Djambala", type: "department" },
        { id: "cg-20", name: "Pool", capital: "Kinkala", type: "department" },
        { id: "cg-21", name: "Sangha", capital: "Ouesso", type: "department" },
      ],
    },
    {
      id: "ga",
      name: "Gabon",
      code: "GA",
      region: "Central Africa",
      subregion: "Central Africa",
      capital: "Libreville",
      population: 2225734,
      area: 267668,
      languages: ["French"],
      currencies: ["XAF"],
      timezones: ["UTC+1"],
      flag: "🇬🇦",
      states: [
        { id: "ga-1", name: "Estuaire", capital: "Libreville", type: "province" },
        { id: "ga-2", name: "Haut-Ogooué", capital: "Franceville", type: "province" },
        { id: "ga-3", name: "Moyen-Ogooué", capital: "Lambaréné", type: "province" },
        { id: "ga-4", name: "Ngounié", capital: "Mouila", type: "province" },
        { id: "ga-5", name: "Nyanga", capital: "Tchibanga", type: "province" },
        { id: "ga-6", name: "Ogooué-Ivindo", capital: "Makokou", type: "province" },
        { id: "ga-7", name: "Ogooué-Lolo", capital: "Koulamoutou", type: "province" },
        { id: "ga-8", name: "Ogooué-Maritime", capital: "Port-Gentil", type: "province" },
        { id: "ga-9", name: "Woleu-Ntem", capital: "Oyem", type: "province" },
      ],
    },
    {
      id: "td",
      name: "Chad",
      code: "TD",
      region: "Central Africa",
      subregion: "Central Africa",
      capital: "N'Djamena",
      population: 16425864,
      area: 1284000,
      languages: ["French", "Arabic"],
      currencies: ["XAF"],
      timezones: ["UTC+1"],
      flag: "🇹🇩",
      states: [
        { id: "td-bg", name: "Bahr el Gazel", capital: "Moussoro", type: "region" },
        { id: "td-ba", name: "Batha", capital: "Ati", type: "region" },
        { id: "td-bo", name: "Borkou", capital: "Faya-Largeau", type: "region" },
        { id: "td-cb", name: "Chari-Baguirmi", capital: "Massenya", type: "region" },
        { id: "td-en", name: "Ennedi", capital: "Fada", type: "region" },
        { id: "td-gu", name: "Guéra", capital: "Mongo", type: "region" },
        { id: "td-hi", name: "Hadjer-Lamis", capital: "Massakory", type: "region" },
        { id: "td-ka", name: "Kanem", capital: "Mao", type: "region" },
        { id: "td-la", name: "Lac", capital: "Bol", type: "region" },
        { id: "td-lc", name: "Logone Occidental", capital: "Moundou", type: "region" },
        { id: "td-lr", name: "Logone Oriental", capital: "Doba", type: "region" },
        { id: "td-me", name: "Mandoul", capital: "Koumra", type: "region" },
        { id: "td-mo", name: "Mayo-Kebbi Est", capital: "Bongor", type: "region" },
        { id: "td-mw", name: "Mayo-Kebbi Ouest", capital: "Pala", type: "region" },
        { id: "td-nd", name: "N'Djamena", capital: "N'Djamena", type: "region" },
        { id: "td-od", name: "Ouaddaï", capital: "Abéché", type: "region" },
        { id: "td-sa", name: "Salamat", capital: "Am Timan", type: "region" },
        { id: "td-si", name: "Sila", capital: "Goz Beïda", type: "region" },
        { id: "td-ti", name: "Tandjilé", capital: "Laï", type: "region" },
        { id: "td-ta", name: "Tibesti", capital: "Bardaï", type: "region" },
        { id: "td-wf", name: "Wadi Fira", capital: "Biltine", type: "region" },
      ],
    },
    {
      id: "cf",
      name: "Central African Republic",
      code: "CF",
      region: "Central Africa",
      subregion: "Central Africa",
      capital: "Bangui",
      population: 4829767,
      area: 622984,
      languages: ["French", "Sango"],
      currencies: ["XAF"],
      timezones: ["UTC+1"],
      flag: "🇨🇫",
      states: [
        { id: "cf-bb", name: "Bamingui-Bangoran", capital: "Ndele", type: "prefecture" },
        { id: "cf-bk", name: "Bangui", capital: "Bangui", type: "commune" },
        { id: "cf-bg", name: "Basse-Kotto", capital: "Mobaye", type: "prefecture" },
        { id: "cf-kb", name: "Gribingui", capital: "Kaga-Bandoro", type: "economic prefecture" },
        { id: "cf-hm", name: "Haut-Mbomou", capital: "Obo", type: "prefecture" },
        { id: "cf-hk", name: "Haute-Kotto", capital: "Bria", type: "prefecture" },
        { id: "cf-hs", name: "Haute-Sangha", capital: "Nola", type: "economic prefecture" },
        { id: "cf-kg", name: "Kémo", capital: "Sibut", type: "prefecture" },
        { id: "cf-lb", name: "Lobaye", capital: "Mbaiki", type: "prefecture" },
        { id: "cf-mb", name: "Mbomou", capital: "Bangassou", type: "prefecture" },
        { id: "cf-nm", name: "Nana-Mambéré", capital: "Bouar", type: "prefecture" },
        { id: "cf-mp", name: "Ombella-Mpoko", capital: "Bimbo", type: "prefecture" },
        { id: "cf-uk", name: "Ouaka", capital: "Bambari", type: "prefecture" },
        { id: "cf-ac", name: "Ouham", capital: "Bossangoa", type: "prefecture" },
        { id: "cf-op", name: "Ouham-Pendé", capital: "Bozoum", type: "prefecture" },
        { id: "cf-se", name: "Sangha-Mbaéré", capital: "Nola", type: "economic prefecture" },
        { id: "cf-vk", name: "Vakaga", capital: "Birao", type: "prefecture" },
      ],
    },
    {
      id: "gq",
      name: "Equatorial Guinea",
      code: "GQ",
      region: "Central Africa",
      subregion: "Central Africa",
      capital: "Malabo",
      population: 1402985,
      area: 28051,
      languages: ["Spanish", "French", "Portuguese"],
      currencies: ["XAF"],
      timezones: ["UTC+1"],
      flag: "🇬🇶",
      states: [
        { id: "gq-an", name: "Annobón", capital: "San Antonio de Palé", type: "province" },
        { id: "gq-bn", name: "Bioko Norte", capital: "Malabo", type: "province" },
        { id: "gq-bs", name: "Bioko Sur", capital: "Luba", type: "province" },
        { id: "gq-cs", name: "Centro Sur", capital: "Evinayong", type: "province" },
        { id: "gq-kn", name: "Kié-Ntem", capital: "Ebebiyín", type: "province" },
        { id: "gq-li", name: "Litoral", capital: "Bata", type: "province" },
        { id: "gq-wn", name: "Wele-Nzas", capital: "Mongomo", type: "province" },
      ],
    },
    {
      id: "st",
      name: "São Tomé and Príncipe",
      code: "ST",
      region: "Central Africa",
      subregion: "Middle Africa",
      capital: "São Tomé",
      population: 219159,
      area: 964,
      languages: ["Portuguese"],
      currencies: ["STN"],
      timezones: ["UTC+0"],
      flag: "🇸🇹",
      states: [
        { id: "st-pa", name: "Príncipe", capital: "Santo António", type: "province" },
        { id: "st-st", name: "São Tomé", capital: "São Tomé", type: "province" },
      ],
    },
  ];
  
  // Combine all countries
  export const allAfricanCountries: Country[] = [
    ...africanCountries.slice(0, 6), // North Africa
    ...africanCountries.slice(6, 11), // West Africa
    ...africanCountries.slice(11, 19), // East Africa
    ...africanCountries.slice(19, 27), // Southern Africa
    ...centralAfricanCountries,
  ];
  
  // Helper functions
  export const getCountryByCode = (code: string): Country | undefined => {
    return allAfricanCountries.find(c => c.code === code.toUpperCase());
  };
  
  export const getCountryByName = (name: string): Country | undefined => {
    return allAfricanCountries.find(c => c.name.toLowerCase() === name.toLowerCase());
  };
  
  export const getCountriesByRegion = (region: string): Country[] => {
    return allAfricanCountries.filter(c => c.region === region);
  };
  
  export const getStatesByCountry = (countryCode: string): State[] => {
    const country = getCountryByCode(countryCode);
    return country?.states || [];
  };
  
  export const getCountryOptions = () => {
    return allAfricanCountries.map(country => ({
      value: country.code,
      label: country.name,
      flag: country.flag,
      region: country.region,
    }));
  };
  
  export const getStateOptions = (countryCode: string) => {
    const states = getStatesByCountry(countryCode);
    return states.map(state => ({
      value: state.id,
      label: state.name,
      type: state.type,
    }));
  };
  